title: rupertbenbrook.com
description: Random technological babblings
theme: jekyll-theme-cayman
lang: en-GB

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Rupert Benbrook"
      comments: true

#gems:
#  - jekyll-sitemap
#  - jekyll-feed
