title: rupertbenbrook.com
description: Random technological babblings
theme: jekyll-theme-cayman
lang: en-GB

defaults:
  -
    scope:
      path: ""
      type: "post"
    values:
      comments: true

#gems:
#  - jekyll-sitemap
#  - jekyll-feed
